name: ZAP Scan

on:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start Flask App
        run: |
          pip install -r requirements.txt
          nohup python app.py &
          sleep 5

      - name: Run ZAP Baseline Scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py \
            -t http://host.docker.internal:5000 \
            -r zap_report.html
